[package]
name= "sdl2_game_engine"
version = "0.0.1"
authors = ["Aleksandr Poltarjonok aka Codenator81 <codenator81@gmail.com>"]

[lib]
name = "sdl2_game_engine"
path = "src/lib.rs"

[dependencies]
    sdl2 = "*"
    sdl2_image = "*"